### ISSUE TITLE
URL Encoder/Decoder Doesn't Show-up

### ISSUE THREAD

**Issue by SoulHarsh007** [CharithBhat/DevArmory#1]
![image](https://user-images.githubusercontent.com/57407752/197027154-b99e864b-6a1b-41b7-9d90-7193a5c4919a.png)

The URL encoder/decoder tab does not show-up correctly, all I see is a blank tab. All other tools seem to work correctly.

Additional Information:

- VSCode Version: 1.73.0-insider
- Extension Version: CharithBhat.devarmory@0.0.19

**Comment by CharithBhat** [comment]
Hey @SoulHarsh007, Thanks for pointing it out. 

The issue hasn't been encountered by other users of the extension. It could have something to do with that specific version of VS Code (VSCode Version: 1.73.0-insider) I think. Will try to reproduce and resolve it!

**Comment by SoulHarsh007** [comment]
![image](https://user-images.githubusercontent.com/57407752/197568866-5cf02f8d-31b0-44ed-ac30-e417b4a5fa66.png)

Hello, I have tested the extension on my fresh installation of Visual Studio Code (Version: 1.72.2), I am still facing the same issue.

**Comment by CharithBhat** [comment]
Hey @SoulHarsh007, thanks for the insight!

If it isn't too much to ask, Can you send a screenshot of your Webview Developer tools for the  Url encoder/decoder screen?

To do that:
a) First go to the Url encoder/ decoder screen and open the command palette (ctrl + shift + p) from there.
b) Search for "Open Webview Developer Tools" and click.

![image](https://user-images.githubusercontent.com/41634502/197685642-807227da-b2e5-464a-af4e-7792f41e4320.png)

c) It should open up the Webview debugger on the right. A screenshot of that could tell me what's happening.

![image](https://user-images.githubusercontent.com/41634502/197684784-739e0488-a53d-413b-8891-deb43b3b6010.png)

Also what Operating System are you on?

**Comment by SoulHarsh007** [comment]
Screenshot with WebView developer tools:
![image](https://user-images.githubusercontent.com/57407752/197869466-9b7a1a8a-74ac-4dc5-b503-4e5fa7e276fc.png)

OS: Arch Linux [Kernel: 6.0.2-zen1-1.1-zen]

If you need the log output in a logfile, please let me know!

<details>
<summary>
Logs:
</summary>
Error: Unable to read file '/home/soulharsh007/.vscode-insiders/extensions/charithbhat.devarmory-0.0.19/out/compiled/URL.css' (Error: Unable to resolve nonexistent file '/home/soulharsh007/.vscode-insiders/extensions/charithbhat.devarmory-0.0.19/out/compiled/URL.css')
    at d.doReadFileStream (fileService.ts:573:11)
    at async C (resourceLoading.ts:68:18)
    at async s.loadResource (webviewElement.ts:779:19)
<hr>
GET https://file+.vscode-resource.vscode-cdn.net/home/soulharsh007/.vscode-insiders/extensions/charithbhat.devarmory-0.0.19/out/compiled/URL.css net::ERR_ABORTED 404
<hr>
Error: Unable to read file '/home/soulharsh007/.vscode-insiders/extensions/charithbhat.devarmory-0.0.19/out/compiled/URL.js' (Error: Unable to resolve nonexistent file '/home/soulharsh007/.vscode-insiders/extensions/charithbhat.devarmory-0.0.19/out/compiled/URL.js')
    at d.doReadFileStream (fileService.ts:573:11)
    at async C (resourceLoading.ts:68:18)
    at async s.loadResource (webviewElement.ts:779:19)
<hr>
GET https://file+.vscode-resource.vscode-cdn.net/home/soulharsh007/.vscode-insiders/extensions/charithbhat.devarmory-0.0.19/out/compiled/URL.js net::ERR_ABORTED 404
(anonymous) @ index.html?id=3ae64ca2-1db6-4645-90d2-b3b913b3f119&origin=67c5fa53-f562-4743-80f9-046168cb59af&swVersion=4&extensionId=CharithBhat.devarmory&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:969
setTimeout (async)
onFrameLoaded @ index.html?id=3ae64ca2-1db6-4645-90d2-b3b913b3f119&origin=67c5fa53-f562-4743-80f9-046168cb59af&swVersion=4&extensionId=CharithBhat.devarmory&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:967
(anonymous) @ index.html?id=3ae64ca2-1db6-4645-90d2-b3b913b3f119&origin=67c5fa53-f562-4743-80f9-046168cb59af&swVersion=4&extensionId=CharithBhat.devarmory&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:998
</details>

**Comment by CharithBhat** [comment]
Thanks! looks like for some reason, it doesn't find the compiled files. Weird. Will do a bit of digging and get to the bottom of it as soon as I can!
